accounts/urls.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import path,re_path, reverse_lazy
from django.contrib.auth import views as auth_views
from accounts import views


urlpatterns = [
    path('signup/', views.signup, name = 'signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit/', views.profile_edit, name='profile_edit'),
    path('password_change/', views.Password_Change_View.as_view(), name='password_change'),
    re_path(r'^(?P<username>[\w.@+-]+)/follow/$', views.user_follow, name='user_follow'),
    re_path(r'^(?P<username>[\w.@+-]+)/unfollow/$', views.user_unfollow, name='user_unfollow'),

]

dinstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import RedirectView
from django_pydenticon.urls import image as pydenticon_image



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='instagram:index'), name='root'),
    path('accounts/', include('accounts.urls')),
    path('identicon/image/<path:data>', pydenticon_image, name='pydenticon_image'),
    path('instagram/', include('instagram.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

instagram/urls.py
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.urls import path, re_path

from instagram import views

app_name = 'instagram'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>', views.post_detail, name='post_detail'),
    re_path(r'^(?P<username>[\w.@+-]+)/$', views.user_page, name='user_page'),
    path('post/<int:pk>/like/', views.post_like, name='post_like'),
    path('post/<int:pk>/unlike/', views.post_unlike, name='post_unlike'),
    # comment의 pk와 혼동되지 않게 post_pk라고 따로 지정
    path('post/<int:post_pk>/comment/new/', views.comment_new, name='comment_new'),
    ]

dinstagram/templates/_form.html
{% load bootstrap4 %}



<div class="card">
    {% if form_title %}
        <div class="card-header" style="text-align: center;">
            {{ form_title }}
        </div>
    {% endif %}
    <div class="card-body" style="text-align: center;">
        {% if form %}
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                <button type="submit" class="btn btn-primary">
                    {{ submit_label|default:"submit" }}
                </button>
                {% endbuttons %}
            </form>
        {% else %}
            <div class="alert alert-danger">
                Form을 지정해주세요!
            </div>
        {% endif %}

    </div>

</div>

dinstagram/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dinstagram</title>
    <link rel="stylesheet" href="{% static 'bootstrap-5.1.3-dist/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="//pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'bootstrap-5.1.3-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'jquery.form-4.3.0.min.js' %}"></script>

</head>
<body>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert={{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="width: 100%;height: 60px;">
    <div class="container">
        <a href="{% url 'instagram:index' %}">
        <img style="height: 30px; object-fit: contain"
             src="https://www.instagram.com/static/images/web/mobile_nav_type_logo-2x.png/1b47f9d0e595.png">
        </a>
    <input class="form-control" style="width: 200px" type="search" placeholder="Search" aria-label="Search">
    <div>
        <a class="p-2 text-dark text-decoration-none" href="{% url 'instagram:index' %}">
            <svg aria-label="x홈" class="_8-yf5 " color="#262626" fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22"><path d="M45.5 48H30.1c-.8 0-1.5-.7-1.5-1.5V34.2c0-2.6-2.1-4.6-4.6-4.6s-4.6 2.1-4.6 4.6v12.3c0 .8-.7 1.5-1.5 1.5H2.5c-.8 0-1.5-.7-1.5-1.5V23c0-.4.2-.8.4-1.1L22.9.4c.6-.6 1.6-.6 2.1 0l21.5 21.5c.3.3.4.7.4 1.1v23.5c.1.8-.6 1.5-1.4 1.5z"></path></svg>
        </a>
        <a class="p-2 text-dark text-decoration-none" href="{% url 'instagram:index' %}">
            <svg aria-label="Direct" class="_8-yf5 " color="#262626" fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22"><path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2 6.1h35.5L18 18.7 5.2 6.1zm18.7 33.6l-4.4-18.4L42.4 8.6 23.9 39.7z"></path></svg>
        </a>
        <a class="p-2 text-dark text-decoration-none" href="{% url 'instagram:index' %}">
            <svg aria-label="사람 찾기" class="_8-yf5 " color="#262626" fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22"><path clip-rule="evenodd" d="M24 0C10.8 0 0 10.8 0 24s10.8 24 24 24 24-10.8 24-24S37.2 0 24 0zm0 45C12.4 45 3 35.6 3 24S12.4 3 24 3s21 9.4 21 21-9.4 21-21 21zm10.2-33.2l-14.8 7c-.3.1-.6.4-.7.7l-7 14.8c-.3.6-.2 1.3.3 1.7.3.3.7.4 1.1.4.2 0 .4 0 .6-.1l14.8-7c.3-.1.6-.4.7-.7l7-14.8c.3-.6.2-1.3-.3-1.7-.4-.5-1.1-.6-1.7-.3zm-7.4 15l-5.5-5.5 10.5-5-5 10.5z" fill-rule="evenodd"></path></svg>
        </a>
        <a class="p-2 text-dark text-decoration-none" href="{% url 'instagram:post_new' %}">
            <svg aria-label="새로운 게시물" class="_8-yf5 " color="#262626" fill="#262626" height="24" role="img" viewBox="0 0 24 24" width="24"><path d="M2 12v3.45c0 2.849.698 4.005 1.606 4.944.94.909 2.098 1.608 4.946 1.608h6.896c2.848 0 4.006-.7 4.946-1.608C21.302 19.455 22 18.3 22 15.45V8.552c0-2.849-.698-4.006-1.606-4.945C19.454 2.7 18.296 2 15.448 2H8.552c-2.848 0-4.006.699-4.946 1.607C2.698 4.547 2 5.703 2 8.552z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path><line fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" x1="6.545" x2="17.455" y1="12.001" y2="12.001"></line><line fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" x1="12.003" x2="12.003" y1="6.545" y2="17.455"></line></svg>
        </a>
        <a class="p-2 text-dark text-decoration-none" href="{% url 'instagram:user_page' user %}">
            <svg aria-label="활동 피드" class="_8-yf5 " color="#262626" fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22"><path d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path></svg>
        </a>
        <a class="p-2 text-dark text-decoration-none" href="{% url 'profile_edit' %}">
            <img src="{{ user.avatar_url }}" style="width:24px; height:24px; border-radius: 10px;"/>
            <!-- 아이디 마다 다른 아이콘(프로필 없을때 대체 이미지), pydenticon  -->
        </a>
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

dinstagram/templates/root.html
{%  extends "layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                Instagram
                <hr>
                <a href="{% url 'instagram:post_new' %}" class="btn btn-primary">New Posting</a>
            </div>
        </div>
    </div>
{% endblock %}