accounts/urls.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import path,re_path, reverse_lazy
from django.contrib.auth import views as auth_views
from accounts import views


urlpatterns = [
    path('signup/', views.signup, name = 'signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit/', views.profile_edit, name='profile_edit'),
    path('password_change/', views.Password_Change_View.as_view(), name='password_change'),
    re_path(r'^(?P<username>[\w.@+-]+)/follow/$', views.user_follow, name='user_follow'),
    re_path(r'^(?P<username>[\w.@+-]+)/unfollow/$', views.user_unfollow, name='user_unfollow'),

]

dinstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import RedirectView
from django_pydenticon.urls import image as pydenticon_image



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='instagram:index'), name='root'),
    path('accounts/', include('accounts.urls')),
    path('identicon/image/<path:data>', pydenticon_image, name='pydenticon_image'),
    path('instagram/', include('instagram.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

instagram/urls.py
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.urls import path, re_path

from instagram import views

app_name = 'instagram'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>', views.post_detail, name='post_detail'),
    re_path(r'^(?P<username>[\w.@+-]+)/$', views.user_page, name='user_page'),
    path('post/<int:pk>/like/', views.post_like, name='post_like'),
    path('post/<int:pk>/unlike/', views.post_unlike, name='post_unlike'),
    # comment의 pk와 혼동되지 않게 post_pk라고 따로 지정
    path('post/<int:post_pk>/comment/new/', views.comment_new, name='comment_new'),
    ]

instagram/models.py
from django.conf import settings
from django.db import models
import re

# Create your models here.
from django.urls import reverse



class Post(models.Model):
    # user.mypost_set : 해당 user가 작성한 포스팅 / user.like_user_set : 해당 유저가 좋아요한 포스팅
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='mypost_set')
    photo = models.ImageField(upload_to="instagram/post/%Y/%m/%d")
    caption = models.CharField(max_length=500)
    tag_set = models.ManyToManyField('Tag',blank=True)
    location = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='like_post_set')


    def __str__(self):
        return self.caption

    # 정규표현식으로 cpation에서 tag 찾아내기
    def extract_tag_list(self):
        tag_name_list = re.findall(r"#([a-zA-Z\dㄱ-힣]+)", self.caption)
        tag_list = []
        for tag_name in tag_name_list:
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)
        return tag_list

    def get_absolute_url(self):
        return reverse("instagram:post_detail", args=[self.pk])
    # 좋아요를 누른 유저인지 반환
    def is_like_user(self, user):
        return self.like_user_set.filter(pk=user.pk).exists()
    # 최신글이 timeline 제일 먼저 오게
    class Meta:
        ordering = ['-id']


class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering= ['-id']

instagram/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['photo', 'caption', 'location']
        # forms 에서는 widgets 통해 수정 가능
        widgets = {
            "caption":forms.Textarea
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["message"]
        widgets = {
            "message": forms.Textarea(attrs={"rows": 1}),
        }

instagram/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from instagram.forms import PostForm, CommentForm
from instagram.models import Tag, Post

@login_required
def index(request):
    # author가 현재 user의 following_set에 포함된 경우만 조회, or 연산위해 Q 사용
    post_list = Post.objects.all()\
    #     .filter(
    #     Q(author__in=request.user.following_set.all()) |
    #     Q(author=request.user)
    # )

    comment_form = CommentForm()
    # 현재 로그인한 user 제외하고 받기
    suggest_user_list = get_user_model().objects.all().exclude(pk=request.user.pk)\
        .exclude(pk__in=request.user.following_set.all()) # follow하고나면 추천목록에서 사라지게
    return render(request, "instagram/index.html",{
        "post_list":post_list,
        "suggest_user_list":suggest_user_list,
        "comment_form": comment_form,
    })

@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag_set.add(*post.extract_tag_list())
            messages.success(request, "포스팅을 완료하였습니다.")
            return redirect(post)
    else:
        form = PostForm
    return render(request, "instagram/post_form.html", {
        "form":form,
    })

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()
    return render(request, "instagram/post_detail.html", {
        "post": post,
        "comment_form": comment_form,
    })

def user_page(request,username):
    page_user = get_object_or_404(get_user_model(), username=username, is_active=True)
    if request.user.is_authenticated:
        # following_set에 page_user의 pk가 포함되어 있는지 확인
        is_follow = request.user.following_set.filter(pk=page_user.pk).exists()
    else:
        is_follow = False

    post_list = Post.objects.filter(author=page_user)
    post_count = post_list.count() # DB에 count 쿼리 수행/ len()은 메모리에 올려서 수행
    return render(request, "instagram/user_page.html", {
        "page_user": page_user,
        "post_list": post_list,
        "post_count":post_count,
        "is_follow":is_follow,
    })

@login_required
def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # 좋아요를누르면 현재 user의 like_user_set에 추가
    post.like_user_set.add(request.user)
    messages.success(request, '좋아요')
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)

@login_required
def post_unlike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.remove(request.user)
    messages.success(request, '좋아요 취소')
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)

@login_required
def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            if request.is_ajax():
                return render(request, "instagram/_comment.html", {
                    "commnet": comment
                })
            return redirect(comment.post)
    else:
        form = CommentForm()
    return render(request, "instagram/comment_form.html", {
        "form" : form,
    })

instagram/templates/instagram/_comment.html
{% load humanize %}

<style>
    .feed_reply{
        padding: 0px 10px;
        display: flex;
        flex-direction: column;
    }    
</style>

<div class="feed_reply">
    <span>
        <strong>{{ comment.author }}</strong>&nbsp;&nbsp;{{ comment.message }}
    </span>
    <small class="text-muted">{{ comment.created_at|naturaltime }}</small>
</div>

instagram/templates/instagram/_post_card.html
{% load bootstrap4 humanize instagram_tags %}

<style>
    .feed_icon{
        padding: 5px 5px 0px 5px;
        display: flex;
        justify-content: space-between;
    }span{
         padding-right: 5px;
    }
    

    .feed_name_txt{
        font-size: 16px;
        padding: 5px 10px;
        font-weight: bold;
    }

    .feed_img{
        width: 100%;
        object-fit: contain;
    }
    
</style>

<div class="card">
    <div class="feed_name_txt">
        <img src="{{ post.author.avatar_url }}" alt="" style="width: 32px; height:32px; border-radius: 15px;">
        <a href="{% url 'instagram:user_page' post.author.username %}" class="text-decoration-none">
            {{ post.author.name }}
        </a>
    </div>
    <div class="feed_img">
        <img src="{{ post.photo.url }}" alt="" style="width:100%;" />
        <div class="feed_icon">
            <div>
            {% if post|is_like_user:user %}
                <a href="{% url 'instagram:post_unlike' post.pk %}" style="color: inherit;" class="text-decoration-none">
                    <svg aria-label="좋아요 취소" class="_8-yf5 " color="#ed4956" fill="#ed4956" height="24" role="img" viewBox="0 0 48 48" width="24"><path d="M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path></svg>
                </a>
            {% else %}
                <a href="{% url 'instagram:post_like' post.pk %} " style="color: inherit;" class="text-decoration-none">
                    <svg aria-label="좋아요" class="_8-yf5 " color="#262626" fill="#262626" height="24" role="img" viewBox="0 0 48 48" width="24"><path d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path></svg>
                </a>
            {% endif %}
            <a href="{% url 'instagram:comment_new' post.pk %}" class="text-decoration-none">
                <svg aria-label="댓글 달기" class="_8-yf5 " color="#262626" fill="#262626" height="24" role="img" viewBox="0 0 48 48" width="24"><path clip-rule="evenodd" d="M47.5 46.1l-2.8-11c1.8-3.3 2.8-7.1 2.8-11.1C47.5 11 37 .5 24 .5S.5 11 .5 24 11 47.5 24 47.5c4 0 7.8-1 11.1-2.8l11 2.8c.8.2 1.6-.6 1.4-1.4zm-3-22.1c0 4-1 7-2.6 10-.2.4-.3.9-.2 1.4l2.1 8.4-8.3-2.1c-.5-.1-1-.1-1.4.2-1.8 1-5.2 2.6-10 2.6-11.4 0-20.6-9.2-20.6-20.5S12.7 3.5 24 3.5 44.5 12.7 44.5 24z" fill-rule="evenodd"></path></svg>
            </a>
            <a href="#">
                <svg aria-label="게시물 공유" class="_8-yf5 " color="#262626" fill="#262626" height="24" role="img" viewBox="0 0 48 48" width="24"><path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2 6.1h35.5L18 18.7 5.2 6.1zm18.7 33.6l-4.4-18.4L42.4 8.6 23.9 39.7z"></path></svg>
            </a>
            </div>
            <div>
                <a href="#">
                    <svg aria-label="저장" class="_8-yf5 " color="#262626" fill="#262626" height="24" role="img" viewBox="0 0 24 24" width="24"><polygon fill="none" points="20 21 12 13.44 4 21 4 3 20 3 20 21" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></polygon></svg>
                </a>
            </div>
        </div>
        <!--post.comment_set.all은 post 변수 내 Comment 모델 클래스를 통해 DB에 저장된 첫번째 레코드를 가져온다-->
        <div id="post-{{ post.pk }}-commnet-list" class="comment-list mt-3 mb-3">
            {% for comment in post.comment_set.all %}
                {% include 'instagram/_comment.html' %}
            {% endfor %}
        </div>


        <div>
            {% for tag in post.tag_set.all %}
                <span class="badge bg-secondary" >
                    #{{ tag.name }}
                </span> 
            {% endfor %}
        </div>

        <div>
            <a href="{{ post.get_absolute_url }}" class="text-muted text-decoration-none">
                <small class="text-muted">
                    {{ post.created_at|naturaltime }}
                </small>
            </a>
        </div>


    </div>
    <div style="display: inline-flex;">
        <form id="post-{{ post.pk }}-comment-form" action="{% url 'instagram:comment_new' post.pk %}" method="POST">
            <div>
            {% csrf_token %}
                <div style="width:800px;">
                    {% bootstrap_form comment_form %} 
                </div>
            </div>
        </form>
        <div style="text-align: right; margin-top:30px">
            <button>게시</button>
        </div>
    </div>
</div>

instagram/templates/instagram/comment_form.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with form_title="댓글 쓰기" submit_label="댓글 쓰기" %}
            </div>
        </div>
    </div>
{% endblock %}

instagram/templates/instagram/index.html
{%  extends "instagram/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-sm-8">
                {% for post in post_list %}
                    <div class="mb-2">
                        {% include "instagram/_post_card.html" %}
                    </div>
                {% empty %}
                    포스팅이 없습니다.
                {% endfor %}
            </div>
            <div class="col-sm-4">
                {% include "instagram/timeline_sidebar.html" %}
            </div>
        </div>
    </div>
{% endblock %}

instagram/templates/instagram/layout.html
{% extends "layout.html" %}

instagram/templates/instagram/post_detail.html
{% extends 'instagram/layout.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% include "instagram/_post_card.html" %}
            </div>
        </div>
    </div>
{% endblock %}

instagram/templates/instagram/post_form.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with form_title="새 게시물 만들기" submit_label="포스팅" %}
            </div>
        </div>
    </div>

{% endblock %}

instagram/templates/instagram/timeline_sidebar.html
<style>
    .recommend_box {
        display: flex;
        justify-content: space-between;
        padding: 5px;
        font-size: 14px;
        font-weight: bold;
        align-items: center;
    }

    .name_content{
        display: flex;
        flex-direction: column;
    }
    
</style>

<div class="d-flex p-2 mb-3">
    <div style="margin-left:0;">
        <img src="{{ user.avatar_url }}" style="width:48px; height:48px;" class="rounded-circle">
    </div>
    <div style="margin-left:25px">
        {{ user.username }}<br>
        <small class="text-muted">{{ user.name }}</small>
    </div>
</div>

<div>
    <div class="recommend_box">
        <span style="color: gray"> 회원님을 위한 추천</span>
        <span style="font-size: 12px"> 모두 보기 </span>
    </div>
    <div class="name_content">
        {% for suggested_user in suggest_user_list%}
            {% include "instagram/timeline_sidebar_user_follow.html" %}
        {% empty %}
            추천 친구가 없습니다.
        {% endfor %}
    </div>

</div>

instagram/templates/instagram/timeline_sidebar_user_follow.html
<style>
    .name_content_txt{
        font-size: 12px;
        padding: 0px 10px;
        font-weight: bold;
        color: lightgray;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        width: 190px;
    }
</style>

<div class="d-flex mb-2">
  <div class="p-2">
      <img src="{{ suggested_user.avatar_url }}" style="width:32px; height:32px" class="rounded-circle">
  </div>
  <div class="name_content">
      <a href="{% url 'instagram:user_page' suggested_user.username %}" style="text-decoration: none; font-size: 20px; padding-left: 10px; color:black">
          {{ suggested_user.username }}
      </a>
      <span class="name_content_txt"> 회원님을 위한 추천</span>
  </div>
  <div class="ms-auto p-2">
      <a href="{% url 'user_follow' suggested_user.username %}" class="text-decoration-none" style="font-size: 20px;">팔로우</a>
  </div>
</div>

instagram/templates/instagram/user_page.html
{% extends "instagram/layout.html" %}
{% load thumbnail %}

{% block content %}
    <div class="container">
        <div class="row pt-5 pb-5">
            <div class="col-sm-3" style="text-align: center;">
                <img src="{{ page_user.avatar_url }}" class="rounded-circle" style="width:160px;">
            </div>
            <div class="col-sm-9" style="margin-bottom: 50px;">
                {{ page_user }}
                <a href="{% url 'profile_edit' %}" class="btn btn-primary">
                    Edit_Profile
                </a>
                <!-- follow, unfollow 상황따라 버튼-->
                {% if is_follow %}
                    <a href="{% url 'user_unfollow' page_user.username %}" class="text-decoration-none">UnFollow</a>
                {% else %}
                    <a href="{% url 'user_follow' page_user.username %}" class="text-decoration-none">Follow</a>
                {% endif %}
                <hr/>
                {{ post_count }} posts, 0 followers, 0 following
                <hr/>
                {{ page_user }}
            </div>
            <div class="row">
                {% for post in post_list %}
                    <div class="col-sm-4 mb-3">
                        <img src="{% thumbnail post.photo 512x512 crop %}" alt="{{ post.caption }}" style="width:100%" />
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}